### ISSUE TITLE
Ineligible Repository For Hacktoberfest

### ISSUE THREAD

**Issue by vnksnkr** [ritwik12/Virtual-Assistant#106]
I got started with open source through this project in spirit of taking part in Hacktoberfest. Seems like my PR didnt get counted as it shows this repo as ineligible :\ . Any idea why that happened ? 
Thanks!

**Comment by ritwik12** [comment]
@vnksnkr I am not sure, all other PRs got counted. Also I added the Topic `hacktoberfest` too once I got to know about that. Maybe your PR got in the way of that when they started using hacktoberfest topic for eligible repositories. You could have told me about that then I would've marked your PR eligible. Let me try if possible now.

**Comment by ritwik12** [comment]
If it helps now, I have marked #102 with `hacktoberfest-accepted` label.
