### ISSUE TITLE
Introduce make install and uninstall in makefile

### ISSUE THREAD

**Issue by anindyasen** [ritwik12/Virtual-Assistant#107]
make install will install the binary and other dependencies in /usr/bin, this will help to run virtual_assistant accessible from anywhere. Uninstall will clean up the changes.

**Comment by ritwik12** [comment]
@anindyasen How will someone execute it? For now one need to do `./build/virtual_assistant` after make.
Please update readme too accordingly.

**Comment by anindyasen** [comment]
after make
sudo make install 
then "virtual_assistant" will run it from any location
to remove the changes:
sudo make uninstall

**Comment by ritwik12** [comment]
Ohk, that works fine. Thanks a lot!!
