### ISSUE TITLE
[ideas pls] what to contribute

### ISSUE THREAD

**Issue by SANTHOSH-MAMIDISETTI** [ritwik12/Virtual-Assistant#134]
Hello , I am Santhosh and  am new to open-source and all .This Virtual assistant seems interesting for me , it would be highly appreciated if u can give me some ideas for me to start and work with and so that I may be able to comtribute :) Thanks

**Comment by ritwik12** [comment]
@SANTHOSH-MAMIDISETTI Hey, thanks for your interest in this. Please go through the project once. Try to make it work in your system. Look for any open issues or anything you might want to add to this. 

Let me know if any help needed.
