### ISSUE TITLE
Code readability issues

### ISSUE THREAD

**Issue by danjod99** [ritwik12/Virtual-Assistant#17]
Your idea seems interesting but after quick look at the repository I noticed some alarming problems with style of your code and overall structure. To begin with, your project consists of just *ONE* file and, which is even worse, only *ONE* function that is somewhere around 400 lines long. There is a serious need to split sections of your main function into multiple functions to make maintenance and readability easier. I would also suggest adapting some folders' structure and splitting your code into multiple files.

I also couldn't help the feeling that some parts of your code are duplicated and moreover probably unnecessary as functions performing those task might be provided in standard library.

If you find my statements useful or need some explanations, feel free to email me.

**Comment by ritwik12** [comment]
@danjod99 Well thanks a lot for your view but I did  that on purpose because when I started it . I needed contributors that were beginners and beginners find it problamatic with lots of files.
But now I took it to another level, now it will be a good time to do it in a standard way.

**Comment by ritwik12** [comment]
@danjod99 I would like your help in this if you can, feel free to create an issue and send a PR.

**Comment by danjod99** [comment]
@ritwik12 Thanks for your trust, but due to lack of time I can't contribute actively to the code itself, especially that I use mainly C++ and my knowledge of C is very basic.

**Comment by ritwik12** [comment]
@danjod99 That's ohk, try to help whenever you can.
I am also having a shortage of time nowadays so it will take me time to do what you said.

**Comment by speedy-software-ch** [comment]
i don't have a shortage of time actually, and already working on the code, though i'm a re beginner. used to code win32 API and SDL stuff back in the days (more than 10 years ago) and want to get back on coding. I just need some motivation and mental reassurance (; lol

**Comment by ritwik12** [comment]
@speedy-software-ch We would like your help on this issue if you can. :)

**Comment by sihussain2** [comment]
I would like to help. but this is my first time in github. how can i help? i am an experience C developer

**Comment by speedy-software-ch** [comment]
@sihussain2 ahlan wa sahalan. min wein inti?

**Comment by ritwik12** [comment]
@sihussain2 Hey, thanks for taking interest, I would advice you to get familier with Github and then just fork my repo and make changes to your forked repo and then after making changes send a PR

**Comment by sihussain2** [comment]
Alrighty. I will do it this weekend

**Comment by ritwik12** [comment]
@johntabor  Thanks!!....... That'll be of great help

**Comment by igo4Jesus** [comment]
I have tried doing some clean up on  the code in main.c. Sharing it soon

**Comment by ritwik12** [comment]
@igo4Jesus very nice work. I have checked your work. it's working fine. Please send a PR and do check for Identations and any typos in the files. Also name them accordingly.

**Comment by ritwik12** [comment]
Closing this. solved in #31
