### ISSUE TITLE
Adding details about how to run the program in Readme file

### ISSUE THREAD

**Issue by theprototype** [ritwik12/Virtual-Assistant#28]
I find it a bit hard to know how to compile and run this program as there are some things to be added to the command while compiling like -std=c99 -lcurl -ljson. I am using the following way to compile " gcc main.c -o a -std=c99 -lcurl -ljson ". Is this the correct way or is there any other easy way I am missing.

**Comment by ritwik12** [comment]
@theprototype try gcc main.c $(pkg-config --libs --cflags libcurl) -l json std=gnu11

**Comment by ritwik12** [comment]
@theprototype You may edit the readme too for that.

**Comment by ritwik12** [comment]
closing it as it's already solved.
