### ISSUE TITLE
libjson0 deprecated or dependency issue with Ubuntu 17.10 (Artful Aardvark)

### ISSUE THREAD

**Issue by ellisken** [ritwik12/Virtual-Assistant#33]
Attempting to install the transitional packages libjson0/libjson0-dev `$ sudo apt-get install libjson0 libjson0-dev` during setup on Ubuntu 17.10 results in the following issue: 
`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`E: Unable to locate package libjson0`
`E: Unable to locate package libjson0-dev`

Replacing libjson0-dev with libjson-c-dev (see https://packages.debian.org/source/jessie/json-c) in the following manner seems to have solved this problem for me while installing Virtual-Assistant:
`sudo apt-get install libjson-c-dev`

Please note that this also requires updating the compile statement to:
`gcc main.c $(pkg-config --libs --cflags libcurl) -l **json-c** -std=gnu11'

And in main.c, `#include <json/json.h>` must be replaced with:
`#include <json-c/json_object.h>`
`#include <json-c/json_tokener.h>`

I would be happy to commit the patch if the developers consider it useful.

**Comment by ritwik12** [comment]
@ellisken Thanks for your contribution, sorry for the delay. It usually never happens. This time I was really busy.
