### ISSUE TITLE
Categories like weather etc in enum

### ISSUE THREAD

**Issue by pardeepsharma89** [ritwik12/Virtual-Assistant#35]
An enum can be created of all categories and based on that rewriting of arrays and other functionality code can be handled. In future, if more categories are added, functionality should be handled automatically.

**Comment by ritwik12** [comment]
@pardeepsharma89 Great, I would like to see the implementation of this. Feel free to send a PR.

**Comment by mcavazotti** [comment]
And you can close this one too :grin:

**Comment by ritwik12** [comment]
@mcavazotti YEah, This can be closed. Thanks!!
