### ISSUE TITLE
Find a new way to check highest score from patter classifier, instead of nested IF/ELSE

### ISSUE THREAD

**Issue by harrywaugh** [ritwik12/Virtual-Assistant#38]

**Comment by ritwik12** [comment]
@hw16471 Hey, thanks for raising this issue. I am aware of this from the moment I wrote the whole code. But the problem is that the functionality of virtual assistant is in such a way that this is the best option possible. If you can try some other way keeping the working intact. Please proceed.

**Comment by rthugh02** [comment]
Hello,

I have began working on a solution to this issue and will be taking it on if that's okay with you.

**Comment by ritwik12** [comment]
@rthugh02 Good work!!

**Comment by mcavazotti** [comment]
Hey, shouldn't this issue be closed?

**Comment by ritwik12** [comment]
@mcavazotti Yea, Thanks for the reminder.
