### ISSUE TITLE
Feature : Weather

### ISSUE THREAD

**Issue by riya-17** [ritwik12/Virtual-Assistant#4]
Get to Know the weather forecast for any location.

**Comment by speedy-software-ch** [comment]
don't we want to implement the curl stuff in this feature the same as for Restaurants?

**Comment by ritwik12** [comment]
@speedy-software-ch This feature works great.we are already using curl in this

**Comment by speedy-software-ch** [comment]
yeah but over the system command and not the library

**Comment by ritwik12** [comment]
@speedy-software-ch Yes, but that does the work in a good and easy way.If there is any benefit in doing some other way, then we will absolutely like to do that.Please let me know

**Comment by speedy-software-ch** [comment]
just for consistency and making sure we don't blow up the dependencies list to fast.

**Comment by ritwik12** [comment]
I appreciate your point. But the current feature gives the desired output and also the output is very attractive. It might be possible that your method will be better than this. But I don't want you out anyone work hard and later realize that the old one was better. Please try and submit a PR if you are confident that it'll be better than the present one.
