### ISSUE TITLE
blank spaces

### ISSUE THREAD

**Issue by pavan-pan** [ritwik12/Virtual-Assistant#46]
When nothing is provided as an input, still firefox is invoked to google.

**Comment by ritwik12** [comment]
@pavan-pan That's a bug I guess. thanks for finding it. do you want to take this issue?

**Comment by pavan-pan** [comment]
Sure Thanks!!

**Comment by pavan-pan** [comment]
I have add the changes. Please review. 

Thanks

**Comment by ritwik12** [comment]
@pavan-pan Thanks for sending PR
