### ISSUE TITLE
ALSA lib pcm_dmix.c:1108 error

### ISSUE THREAD

**Issue by Ngugisenior** [ritwik12/Virtual-Assistant#55]
I keep getting this error when I try to run the command `say "hello"`

`ALSA lib pcm_dmix.c:1108 : ( snd_pcm_open )` unable to open slave `audio_open_alsa`: failed to open audio device default. Device or resource busy.

I have no other application using an audio device, `Ubuntu-19.04`.

**Comment by ritwik12** [comment]
@Ngugisenior Please try “say hello” in your terminal. maybe you have some issue with GNU SPEECH ENGINE

**Comment by Ngugisenior** [comment]
Thanks, works after rebooting `say "hello"`

**Comment by ritwik12** [comment]
@Ngugisenior That's great. Happy to know
