### ISSUE TITLE
Create a Makefile

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Virtual-Assistant#73]

**Comment by mudaliaraditya** [comment]
I would like to do the makefile part of this project

**Comment by ritwik12** [comment]
Hey @mudaliaraditya, last I heard @omerdagan84 was working on it.
@omerdagan84  Please let us know if you are done or this issue is good to be taken for @mudaliaraditya

**Comment by hardikpnsp** [comment]
Is someone still working on this? I would like to take this up if not, I can try to debug the Makefile present in the PR or make a new one from scratch as it is not working for me either.

**Comment by ritwik12** [comment]
@hardikpnsp Please go ahead, Thanks for taking interest.
