### ISSUE TITLE
Add basic math capabilities

### ISSUE THREAD

**Issue by Eldart95** [ritwik12/Virtual-Assistant#84]
i would like to contribute basic math capabilities to the assistant (and update the readme of course), what do you think about that ?

**Comment by ritwik12** [comment]
That will be good. can you add some complex maths too in addition to basic maths? That will be great.

**Comment by Eldart95** [comment]
sure, i was thinking about addition,subtraction,multiplication,division,power and reminder.
anything else ?

**Comment by ritwik12** [comment]
@Eldart95 That will be great for basics. Let's first do that

**Comment by Eldart95** [comment]
while i was implementing the calculator i realized that it would be better to use the command line - calculator - as it has many capabilities.
i also added an calculator feature witch brings up the calculator.
readme also has been updated.
i made a push request for your review.

**Comment by ritwik12** [comment]
@Eldart95 Ohk, Will review. Thanks :)

**Comment by ritwik12** [comment]
Thanks @Eldart95, nice contribution to Virtual Assistant. 
Closing this being merged
