### ISSUE TITLE
Restaurant

### ISSUE THREAD

**Issue by ritwik12** [ritwik12/Virtual-Assistant#9]
Just like we are getting the weather forecast, we can even get the list of restaurants near us.

**Comment by Rushikesh22** [comment]
Hi. I would like to work on this. This would be my first contribution so could you please give me some starting advice?

**Comment by speedy-software-ch** [comment]
welcome on the project. is places api from google free to use,or do they charge? 'cause if it's free maybe there is a possibility to do that over curl.

**Comment by ritwik12** [comment]
Hey @Rushikesh22 
We can use google api for this. But implementing that in C might be a problem.
I have one way of doing it but that is just like our youtube and google search feature.
Here it goes

Algorithm for Google Search
Step1 - Start
Step2 - Read user's input and store it in a string. Example : String = Artificial Intelligence
Replace all the blank spaces with \+". Example : String = Artificial+Intelligence
Step3 - Manipulate google url by embedding the string entered by user into the url
Step4 - Define a buffer to hold the string value.
Step5 - Save url in a buffer as a string using sprintf
Step6 - Use buffer value to execute
Step7 - Stop

For restaurants we have 
`https://www.google.co.in/maps/search/restaurants+near+New+York/@40.7441291,-74.0210865,13z/data=!3m1!4b1?dcr=0`
What we do is change this `restaurants+near+New+York` part with whatever we want to search on maps like restaurants near me, etc.
By doing this whenever the user enters restaurants near me or something like that, then a new browser window will open and it will search the users's input into the google maps.
For example see - https://www.google.co.in/maps/search/restaurants+near+New+York/@40.7441291,-74.0210865,13z/data=!3m1!4b1?dcr=0

 I would have implemented it, but it is simple and not so good.So I am looking for something better. At last I will implement this if nothing better is suitable.

**Comment by speedy-software-ch** [comment]
still we could use curl

**Comment by speedy-software-ch** [comment]
still we could use curl

**Comment by ritwik12** [comment]
@speedy-software-ch  Yes we could use it :)

**Comment by Rushikesh22** [comment]
I'm done with this. I've used libcurl with google places API. Will send a pull request soon.

**Comment by ritwik12** [comment]
@Rushikesh22 Great, please send as soon as you can :)

**Comment by ritwik12** [comment]
Merged #15
